
server:
  port: 8080

spring:
  application:
    name: MicroserviceCustomer
  data:
    mongodb:
      uri: mongodb://haroldusername:haroldpassword@ac-yyqiukt-shard-00-00.njg0lhs.mongodb.net:27017,ac-yyqiukt-shard-00-01.njg0lhs.mongodb.net:27017,ac-yyqiukt-shard-00-02.njg0lhs.mongodb.net:27017/?ssl=true&replicaSet=atlas-x44noa-shard-0&authSource=admin&retryWrites=true&w=majority
      database: Reactivoooooo